"""FinVeritas V2 — Core Data Schemas

Defines the internal data models used throughout the system:
- NormalizedCompanyRecord: Source-agnostic company representation
- ProvenancedValue: Financial values with source tracking
- FactLedgerEntry / FinancialFactLedger: Deterministic computation results
- DSCRInputs / DSCRMethodology: DSCR calculation inputs and methodology documentation
- CreditAssessmentReport: Final lender-facing output
- PeerCompany / PeerComparison: Peer benchmarking data

Design principle: All financial math is done in Python. The LLM never touches
raw numbers — it only receives pre-computed fact ledger entries.
"""
from __future__ import annotations

from enum import Enum
from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, Field


# -------------------------------------------------------------------------
# Enums
# -------------------------------------------------------------------------

class RiskLevel(str, Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class FactStatus(str, Enum):
    VALID = "VALID"
    ESTIMATED = "ESTIMATED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class CheckStatus(str, Enum):
    PASS = "PASS"
    WARN = "WARN"
    FAIL = "FAIL"
    SKIP = "SKIP"


# -------------------------------------------------------------------------
# Core Financial Schemas
# -------------------------------------------------------------------------

class FinancialPeriod(BaseModel):
    """A single numeric observation tied to a reporting period."""
    period: str = Field(..., description="e.g. 2023-FY, 2024-Q1")
    value: float = Field(..., description="The financial value for this period")


class ProvenancedValue(BaseModel):
    """A financial value with full source provenance.

    Used for important extracted/computed values where traceability matters
    for explainability and credibility.
    """
    value: float
    unit: str = Field("absolute", description="e.g. absolute, %, ratio, days")
    currency: Optional[str] = Field(None, description="Currency code if monetary value")
    period: Optional[str] = Field(None, description="Reporting period e.g. 2023-FY")
    source: str = Field("unknown", description="Where this value came from: yfinance, fmp, pdf_ocr, user_input, computed")
    extraction_location: Optional[str] = Field(None, description="E.g. 'Income Statement > Operating Income', 'user form'")
    confidence: float = Field(1.0, ge=0.0, le=1.0, description="Confidence score 0-1")
    validation_status: FactStatus = Field(FactStatus.VALID)
    notes: Optional[str] = None


# -------------------------------------------------------------------------
# Fact Ledger — Contract Between Python and Agents
# -------------------------------------------------------------------------

class FactLedgerEntry(BaseModel):
    """A single computed metric in the fact ledger.

    Once generated by the Deterministic Metrics Engine, these values become
    the authoritative financial facts. Agents consume but never modify them.
    """
    metric: str = Field(..., description="Metric identifier e.g. 'revenue_growth_yoy'")
    display_name: str = Field(..., description="Human-readable name e.g. 'YoY Revenue Growth'")
    category: str = Field(..., description="E.g. 'revenue', 'profitability', 'liquidity', 'solvency', 'saas', 'dscr'")
    value: Optional[float] = Field(None, description="Computed value (None if insufficient data)")
    unit: str = Field("absolute", description="E.g. %, ratio, days, absolute")
    period: Optional[str] = Field(None, description="Reporting period")
    formula: Optional[str] = Field(None, description="Formula used: e.g. '(Revenue_T - Revenue_T-1) / Revenue_T-1 * 100'")
    inputs_used: List[str] = Field(default_factory=list, description="Source fields used in calculation")
    status: FactStatus = Field(FactStatus.VALID)
    risk_signal: Optional[CheckStatus] = Field(None, description="PASS/WARN/FAIL if this metric has a threshold")
    risk_detail: Optional[str] = Field(None, description="Why this risk signal was assigned")
    notes: Optional[str] = None


class FinancialFactLedger(BaseModel):
    """Complete set of computed metrics for a company analysis.

    This is the central contract between the deterministic computation layer
    and the agentic reasoning layer. Once computed, these facts are immutable.
    """
    entity_id: str
    analysis_timestamp: str
    currency: Optional[str] = None
    entries: List[FactLedgerEntry] = Field(default_factory=list)

    def get(self, metric: str) -> Optional[FactLedgerEntry]:
        """Retrieve a specific metric entry by name."""
        for e in self.entries:
            if e.metric == metric:
                return e
        return None

    def get_value(self, metric: str) -> Optional[float]:
        """Retrieve just the value for a metric."""
        entry = self.get(metric)
        return entry.value if entry else None

    def by_category(self, category: str) -> List[FactLedgerEntry]:
        """Retrieve all entries for a category."""
        return [e for e in self.entries if e.category == category]

    def risk_signals(self) -> List[FactLedgerEntry]:
        """Return all entries that have a risk signal set."""
        return [e for e in self.entries if e.risk_signal is not None]


# -------------------------------------------------------------------------
# Company Record
# -------------------------------------------------------------------------

class NormalizedCompanyRecord(BaseModel):
    """Standardized internal representation of a company, regardless of source
    (Bloomberg PDF, Ticker, or CSV).

    V2 additions: country, jurisdiction, SaaS classification, company
    description, and provenance tracking.
    """
    entity_id: str = Field(..., description="Company name or ticker symbol")
    source: str = Field(..., description="E.g., bloomberg_pdf, ticker, csv, user_input")
    currency: Optional[str] = Field(None, description="Currency code, e.g., USD, INR")

    # V2: Company identity & classification
    country: Optional[str] = Field(None, description="Country of domicile e.g. 'US', 'IN', 'DE'")
    jurisdiction: Optional[str] = Field(None, description="Primary regulatory jurisdiction")
    industry: Optional[str] = Field(None, description="Industry classification")
    saas_subtype: Optional[str] = Field(None, description="SaaS subcategory e.g. 'CRM', 'HCM', 'Security', 'Infrastructure'")
    company_description: Optional[str] = Field(None, description="Brief description of what the company does")
    is_public: Optional[bool] = Field(None, description="Whether the company is publicly traded")
    ticker_symbol: Optional[str] = Field(None, description="Stock ticker if public")

    # Standard Financials (time series)
    revenue: List[FinancialPeriod] = Field(default_factory=list)
    cost_of_revenue: List[FinancialPeriod] = Field(default_factory=list)
    gross_profit: List[FinancialPeriod] = Field(default_factory=list)
    operating_income: List[FinancialPeriod] = Field(default_factory=list)
    net_operating_income: List[FinancialPeriod] = Field(default_factory=list)
    ebitda: List[FinancialPeriod] = Field(default_factory=list)
    net_income: List[FinancialPeriod] = Field(default_factory=list)
    interest_expense: List[FinancialPeriod] = Field(default_factory=list)
    depreciation: List[FinancialPeriod] = Field(default_factory=list)
    pretax_income: List[FinancialPeriod] = Field(default_factory=list)
    income_tax: List[FinancialPeriod] = Field(default_factory=list)

    # Balance sheet
    total_assets: List[FinancialPeriod] = Field(default_factory=list)
    total_liabilities: List[FinancialPeriod] = Field(default_factory=list)
    current_assets: List[FinancialPeriod] = Field(default_factory=list)
    current_liabilities: List[FinancialPeriod] = Field(default_factory=list)
    equity: List[FinancialPeriod] = Field(default_factory=list)
    total_debt: List[FinancialPeriod] = Field(default_factory=list)
    long_term_debt: List[FinancialPeriod] = Field(default_factory=list)
    short_term_debt: List[FinancialPeriod] = Field(default_factory=list)
    cash_and_equivalents: List[FinancialPeriod] = Field(default_factory=list)
    non_current_assets: List[FinancialPeriod] = Field(default_factory=list)
    non_current_liabilities: List[FinancialPeriod] = Field(default_factory=list)
    retained_earnings: List[FinancialPeriod] = Field(default_factory=list)
    accounts_receivable: List[FinancialPeriod] = Field(default_factory=list)
    inventory: List[FinancialPeriod] = Field(default_factory=list)
    accounts_payable: List[FinancialPeriod] = Field(default_factory=list)

    # Cash flow statement (V3: critical for real debt-service analysis)
    operating_cash_flow: List[FinancialPeriod] = Field(default_factory=list)
    capital_expenditure: List[FinancialPeriod] = Field(default_factory=list)
    free_cash_flow: List[FinancialPeriod] = Field(default_factory=list)

    # Per-share
    basic_eps: List[FinancialPeriod] = Field(default_factory=list)
    diluted_eps: List[FinancialPeriod] = Field(default_factory=list)

    # SaaS-specific or Derived Info
    saas_metrics: Dict[str, Any] = Field(default_factory=dict, description="e.g. ARR, CAC, NRR if available")
    qualitative_context: Optional[str] = Field(None, description="Extracted management commentary or notes")

    # V2: Provenance
    source_provenance: Dict[str, str] = Field(
        default_factory=dict,
        description="Map of field_name → source (e.g. 'revenue': 'yfinance', 'total_assets': 'fmp')"
    )

    # V3: Currency normalization
    original_currency: Optional[str] = Field(None, description="Native currency before FX conversion, if converted")
    fx_rate_used: Optional[float] = Field(None, description="FX rate applied (1 original_currency = fx_rate base_currency)")
    is_currency_normalized: bool = Field(False, description="True once monetary values are converted to a base currency")

    def latest_value(self, field_name: str) -> Optional[float]:
        """Get the most recent value for a given financial field."""
        series: List[FinancialPeriod] = getattr(self, field_name, [])
        if not series:
            return None
        sorted_series = sorted(series, key=lambda x: x.period)
        return sorted_series[-1].value

    def has_field(self, field_name: str) -> bool:
        """Check if a financial field has any data."""
        series: List[FinancialPeriod] = getattr(self, field_name, [])
        return bool(series)

    # All time-series financial fields (single source of truth).
    FINANCIAL_FIELDS: ClassVar[List[str]] = [
        "revenue", "cost_of_revenue", "gross_profit", "operating_income",
        "net_operating_income", "ebitda", "net_income", "interest_expense",
        "depreciation", "pretax_income", "income_tax",
        "operating_cash_flow", "capital_expenditure", "free_cash_flow",
        "total_assets", "total_liabilities", "current_assets", "current_liabilities",
        "equity", "total_debt", "long_term_debt", "short_term_debt",
        "cash_and_equivalents", "non_current_assets", "non_current_liabilities",
        "retained_earnings", "accounts_receivable", "inventory", "accounts_payable",
        "basic_eps", "diluted_eps",
    ]

    # Fields expressed in currency (converted during FX normalization).
    # Per-share (EPS) values are NOT scaled — they are already per-share amounts,
    # but they ARE currency-denominated, so they are converted too.
    MONETARY_FIELDS: ClassVar[List[str]] = [
        "revenue", "cost_of_revenue", "gross_profit", "operating_income",
        "net_operating_income", "ebitda", "net_income", "interest_expense",
        "depreciation", "pretax_income", "income_tax",
        "operating_cash_flow", "capital_expenditure", "free_cash_flow",
        "total_assets", "total_liabilities", "current_assets", "current_liabilities",
        "equity", "total_debt", "long_term_debt", "short_term_debt",
        "cash_and_equivalents", "non_current_assets", "non_current_liabilities",
        "retained_earnings", "accounts_receivable", "inventory", "accounts_payable",
        "basic_eps", "diluted_eps",
    ]

    def available_fields(self) -> List[str]:
        """Return list of financial fields that have data."""
        return [f for f in self.FINANCIAL_FIELDS if self.has_field(f)]

    def completeness(self) -> Dict[str, Any]:
        """Report which financial fields are present vs missing.

        Returns a dict with present fields, missing fields, and a 0-100 score,
        so the UI can show the user exactly what data was captured before analysis.
        """
        present = self.available_fields()
        missing = [f for f in self.FINANCIAL_FIELDS if f not in present]
        total = len(self.FINANCIAL_FIELDS)
        return {
            "present": present,
            "missing": missing,
            "present_count": len(present),
            "total_count": total,
            "score": round(len(present) / total * 100, 1) if total else 0.0,
        }


# -------------------------------------------------------------------------
# DSCR Schemas
# -------------------------------------------------------------------------

class DSCRInputs(BaseModel):
    """Inputs required for calculating Debt Service Coverage Ratio.

    V2: Extended with loan terms and repayment structure.
    """
    # Existing debt obligations
    existing_loan_principal_repayment: float = Field(0.0, description="Annual principal repayment on existing debt")
    existing_loan_interest: float = Field(0.0, description="Annual interest on existing debt")

    # Proposed new debt
    proposed_loan_principal_repayment: float = Field(0.0, description="Proposed new annual principal repayment")
    proposed_loan_interest: float = Field(0.0, description="Proposed new annual interest")

    # V2: Loan structure details
    proposed_loan_amount: Optional[float] = Field(None, description="Total proposed loan amount")
    proposed_tenure_years: Optional[float] = Field(None, description="Loan tenure in years")
    proposed_interest_rate: Optional[float] = Field(None, description="Annual interest rate as percentage")
    repayment_structure: Optional[str] = Field(None, description="E.g. 'equal_installment', 'bullet', 'balloon'")

    @property
    def total_existing_debt_service(self) -> float:
        return self.existing_loan_principal_repayment + self.existing_loan_interest

    @property
    def total_proposed_debt_service(self) -> float:
        return self.proposed_loan_principal_repayment + self.proposed_loan_interest

    @property
    def total_annual_debt_service(self) -> float:
        return (self.existing_loan_principal_repayment + self.existing_loan_interest +
                self.proposed_loan_principal_repayment + self.proposed_loan_interest)


class DSCRMethodology(BaseModel):
    """Documents the DSCR calculation methodology used.

    Required for explainability — the analyst needs to know exactly how
    DSCR was computed and what assumptions were made.
    """
    numerator_name: str = Field(..., description="E.g. 'EBITDA', 'Operating Income', 'Net Operating Income'")
    numerator_formula: str = Field(..., description="How the numerator was derived")
    numerator_source: str = Field(..., description="Where the numerator data came from")
    denominator_components: List[str] = Field(default_factory=list, description="What's included in debt service")
    time_period: str = Field(..., description="E.g. 'Most recent FY', 'Average of last 3 FY'")
    assumptions: List[str] = Field(default_factory=list, description="Key assumptions made")
    limitations: List[str] = Field(default_factory=list, description="Known limitations of this calculation")
    data_quality_notes: Optional[str] = None


class DSCRResult(BaseModel):
    """Complete DSCR calculation result with methodology."""
    numerator_value: float = Field(..., description="Net operating income / EBITDA used")
    denominator_value: float = Field(..., description="Total annual debt service")
    dscr_ratio: Optional[float] = Field(None, description="DSCR = numerator / denominator")
    risk_level: RiskLevel = Field(RiskLevel.INSUFFICIENT_DATA)
    methodology: DSCRMethodology
    interpretation: Optional[str] = Field(None, description="Context-aware interpretation")


# -------------------------------------------------------------------------
# Peer Analysis Schemas
# -------------------------------------------------------------------------

class PeerCompany(BaseModel):
    """A peer company with actual financial data (not LLM-estimated)."""
    entity_id: str
    ticker: Optional[str] = None
    country: Optional[str] = None
    saas_subtype: Optional[str] = None
    revenue_scale: Optional[str] = None
    peer_tier: str = Field("secondary", description="'primary' (same SaaS subtype + scale) or 'secondary' (broader SaaS)")

    # Actual data (fetched, not hallucinated)
    revenue: Optional[float] = None
    revenue_currency: Optional[str] = None
    revenue_growth: Optional[float] = None
    operating_margin: Optional[float] = None
    gross_margin: Optional[float] = None
    rule_of_40: Optional[float] = None
    debt_to_equity: Optional[float] = None
    current_ratio: Optional[float] = None

    data_source: str = Field("yfinance", description="Where peer data came from")
    data_is_actual: bool = Field(True, description="True = fetched from source, False = estimated")


class PeerComparison(BaseModel):
    """Structured peer benchmarking result."""
    target_entity: str
    peers: List[PeerCompany] = Field(default_factory=list)
    comparison_metrics: Dict[str, Dict[str, Optional[float]]] = Field(
        default_factory=dict,
        description="metric_name -> {target: val, peer_median: val, percentile: val}"
    )
    selection_rationale: str = Field("", description="Why these peers were selected")


# -------------------------------------------------------------------------
# Risk Indicator
# -------------------------------------------------------------------------

class RiskIndicator(BaseModel):
    """A single deterministic risk signal."""
    name: str
    category: str = Field(..., description="profitability, liquidity, solvency, growth, saas, debt_service")
    status: CheckStatus
    value: Optional[float] = None
    threshold: Optional[str] = None
    detail: str = Field("", description="Human-readable explanation")
    severity_weight: float = Field(1.0, description="Relative importance 0-3")


class RiskDashboard(BaseModel):
    """Consolidated risk indicators from all calculators."""
    entity_id: str
    indicators: List[RiskIndicator] = Field(default_factory=list)
    overall_risk: RiskLevel = RiskLevel.MODERATE

    @property
    def fail_count(self) -> int:
        return sum(1 for i in self.indicators if i.status == CheckStatus.FAIL)

    @property
    def warn_count(self) -> int:
        return sum(1 for i in self.indicators if i.status == CheckStatus.WARN)


# -------------------------------------------------------------------------
# Credit Assessment Report — Final Output
# -------------------------------------------------------------------------

class CreditAssessmentReport(BaseModel):
    """The primary output of FinVeritas V2: an explainable credit-risk assessment.

    This is NOT a loan approval/rejection. It is a decision-support document
    for a lending institution or financial analyst.
    """
    entity_id: str
    analysis_date: str
    currency: Optional[str] = None

    # DSCR
    dscr_result: Optional[DSCRResult] = None

    # Financial profile summary
    financial_summary: Dict[str, Any] = Field(default_factory=dict)

    # SaaS analysis
    saas_classification: Optional[str] = None
    saas_metrics: Dict[str, Any] = Field(default_factory=dict)

    # Peer comparison
    peer_comparison: Optional[PeerComparison] = None

    # Risk assessment
    risk_dashboard: Optional[RiskDashboard] = None

    # Qualitative findings
    qualitative_findings: List[str] = Field(default_factory=list)

    # Synthesized assessment
    major_strengths: List[str] = Field(default_factory=list)
    major_risks: List[str] = Field(default_factory=list)
    data_quality_notes: List[str] = Field(default_factory=list)
    missing_information: List[str] = Field(default_factory=list)
    assumptions: List[str] = Field(default_factory=list)

    # Final assessment
    risk_classification: RiskLevel = Field(RiskLevel.MODERATE)
    recommendation_narrative: str = Field("", description="Explainable recommendation for the analyst")

    # Metadata
    methodology_notes: List[str] = Field(default_factory=list)
    disclaimer: str = Field(
        "This assessment is a decision-support tool for qualified analysts. "
        "It does not constitute a loan approval, rejection, or binding credit decision. "
        "The lending institution remains responsible for the final lending decision."
    )
